"""empty message

Revision ID: 191501e47600
Revises: 9c29d30613b4
Create Date: 2019-07-14 19:25:37.046849

"""

# revision identifiers, used by Alembic.
revision = '191501e47600'
down_revision = '9c29d30613b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('k8s_name', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'service', ['k8s_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='unique')
    op.drop_column('service', 'k8s_name')
    # ### end Alembic commands ###
