"""empty message

Revision ID: 9c29d30613b4
Revises: None
Create Date: 2017-05-27 20:31:42.741577

"""

# revision identifiers, used by Alembic.
revision = '9c29d30613b4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('host', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    # ### end Alembic commands ###
